### ISSUE TITLE
Fix licycle loop in `inception` module

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [montblu/terraform-octopusdeploy-bootstrap#28]
Use lookup and add some missing attributes

**Comment by jdaMachado** [comment]
@MiguelNdeCarvalho  Could you add some additional details regarding this bug and how to replicate it?

**Comment by MiguelNdeCarvalho** [comment]
Right now in the `phase` block it only supports `optional_deployment_targets` and I need to use `automatic_deployment_targets` https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/lifecycle#nested-schema-for-phase

**Comment by MiguelNdeCarvalho** [comment]
It was fixed in #30
