### ISSUE TITLE
Worker Pool not being assigned to Deployment Target / Unable to fetch worker pool image

### ISSUE THREAD

**Issue by jdaMachado** [montblu/terraform-octopusdeploy-bootstrap#32]
Currently any deployment target will be considered  unhealthy because our custom worker pool is only being created on the deployment process submodule, not when the deployment targets are configured, which is on the connector submodule. This means that Octopus may use a Windows worker pool as default to check for target's health and will fail fetching our managed workertools package. 

We need to move this resource creation from one submodule to another, correctly assign it to the deployment targets, and then create datasources on the the submodule where the resource previously was, so we can assign it as well to the deployment processes.

**Comment by MiguelNdeCarvalho** [comment]
Fixed in #36
